# Generated by Django 6.0.1 on 2026-01-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rank",
            field=models.CharField(
                choices=[
                    ("B", "Bronze"),
                    ("S", "Silver"),
                    ("G", "Gold"),
                    ("R", "Ruby"),
                    ("D", "Diamond"),
                ],
                max_length=20,
            ),
        ),
    ]
