# Generated by Django 6.0.1 on 2026-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_nickname_alter_customuser_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="poins",
        ),
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rank",
            field=models.CharField(
                choices=[
                    ("B", "Bronze"),
                    ("S", "Silver"),
                    ("G", "Gold"),
                    ("R", "Ruby"),
                    ("D", "Diamond"),
                ],
                default="B",
                max_length=20,
            ),
        ),
    ]
