# Generated by Django 6.0.1 on 2026-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_poins_customuser_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="exp",
            field=models.IntegerField(default=0),
        ),
    ]
