# Generated by Django 6.0.1 on 2026-02-16 12:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_exp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Максимальний розмір: 5MB. Формати: JPG, PNG, GIF",
                null=True,
                upload_to="profile_pictures/",
                validators=[users.models.validate_image_size],
            ),
        ),
    ]
