# Generated by Django 6.0.1 on 2026-02-18 13:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Максимальний розмір: 5MB. Формати: JPG, PNG, GIF",
                null=True,
                upload_to=users.models.get_profile_picture_path,
                validators=[users.models.validate_image_size],
            ),
        ),
    ]
