# Generated by Django 6.0.1 on 2026-02-22 21:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cosmetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("svg_code", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ring", "Ring"),
                            ("rank_ring", "Rank ring"),
                            ("element", "Element"),
                            ("title", "Title"),
                        ],
                        default="ring",
                        max_length=20,
                    ),
                ),
                (
                    "rank_required",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("B", "Bronze"),
                            ("S", "Silver"),
                            ("G", "Gold"),
                            ("R", "Ruby"),
                            ("D", "Diamond"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="active_element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_element_users",
                to="users.cosmetic",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="active_ring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_ring_users",
                to="users.cosmetic",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="active_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_title_users",
                to="users.cosmetic",
            ),
        ),
        migrations.CreateModel(
            name="UserCosmetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "cosmetic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.cosmetic"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "cosmetic")},
            },
        ),
    ]
