# Generated by Django 5.2.6 on 2026-01-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=500)),
                ('improvement_hint', models.CharField(max_length=164)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
