# Generated by Django 6.0.1 on 2026-02-14 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_gamified", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cosmetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("image", models.ImageField(upload_to="cosmetics/")),
            ],
        ),
    ]
