# Generated by Django 6.0.1 on 2026-02-15 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_gamified", "0002_cosmetic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cosmetic",
            name="image",
        ),
        migrations.AddField(
            model_name="cosmetic",
            name="svg",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="cosmetic",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
