# Generated by Django 6.0.1 on 2026-02-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_gamified", "0003_remove_cosmetic_image_cosmetic_svg_cosmetic_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cosmetic",
            old_name="svg",
            new_name="svg_code",
        ),
    ]
