# Generated by Django 6.0.1 on 2026-02-02 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_gamified", "0003_alter_prompt_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="rate",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
