# Generated by Django 6.0.1 on 2026-02-20 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_gamified", "0004_rename_svg_cosmetic_svg_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cosmetic",
            name="user",
        ),
        migrations.AddField(
            model_name="cosmetic",
            name="rank_required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "Bronze"),
                    ("S", "Silver"),
                    ("G", "Gold"),
                    ("R", "Ruby"),
                    ("D", "Diamond"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cosmetic",
            name="type",
            field=models.CharField(
                choices=[
                    ("ring", "Ring"),
                    ("rank_ring", "Rank ring"),
                    ("element", "Element"),
                    ("title", "Title"),
                ],
                default="ring",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cosmetic",
            name="price",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.CreateModel(
            name="UserCosmetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "cosmetic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompt_gamified.cosmetic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "cosmetic")},
            },
        ),
    ]
