# Generated by Django 6.0.1 on 2026-02-20 15:22

from django.db import migrations
from django.conf import settings
from pathlib import Path


cosmetics_data = [
    {
        "name": "Bronze_ring",
        "price": None,
        "svg_code": "cosmetics/bronze_ring.svg",
        "type": "rank_ring",
        "rank_required": None,
    },
    {
        "name": "Silver_ring",
        "price": None,
        "svg_code": "cosmetics/silver_ring.svg",
        "type": "rank_ring",
        "rank_required": "S",
    },
    {
        "name": "Gold_ring",
        "price": None,
        "svg_code": "cosmetics/gold_ring.svg",
        "type": "rank_ring",
        "rank_required": "G",
    },
    {
        "name": "Ruby_ring",
        "price": None,
        "svg_code": "cosmetics/ruby_ring.svg",
        "type": "rank_ring",
        "rank_required": "R",
    },
    {
        "name": "Diamond_ring",
        "price": None,
        "svg_code": "cosmetics/diamond_ring.svg",
        "type": "rank_ring",
        "rank_required": "D",
    },
    {
        "name": "Корона",
        "price": 20,
        "svg_code": "cosmetics/crown.svg",
        "type": "element",
        "rank_required": None,
    },
    {
        "name": "Найкращий вайбкодер",
        "price": 50,
        "svg_code": "cosmetics/best_vibecoder.svg",
        "type": "title",
        "rank_required": None,
    },
    {
        "name": "Майстер копіювання",
        "price": 40,
        "svg_code": "cosmetics/copy_master.svg",
        "type": "title",
        "rank_required": None,
    },
    {
        "name": "Повелитель ШІ",
        "price": 45,
        "svg_code": "cosmetics/ai_lord.svg",
        "type": "title",
        "rank_required": None,
    },
]


def create_cosmetics(apps, schema_editor):
    Cosmetic = apps.get_model("prompt_gamified", "Cosmetic")

    for item in cosmetics_data:
        Cosmetic.objects.get_or_create(
            name=item["name"],
            defaults=item
        )


def delete_cosmetics(apps, schema_editor):
    Cosmetic = apps.get_model("prompt_gamified", "Cosmetic")
    Cosmetic.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        (
            "prompt_gamified",
            "0005_remove_cosmetic_user_cosmetic_rank_required_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(create_cosmetics, delete_cosmetics),
    ]
