# Generated by Django 6.0.1 on 2026-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_gamified", "0006_auto_20260220_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cosmetic",
            name="rank_required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Silver"),
                    ("G", "Gold"),
                    ("R", "Ruby"),
                    ("D", "Diamond"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cosmetic",
            name="svg_code",
            field=models.CharField(),
        ),
    ]
